container:
  image: cirrusci/android-sdk:28
  cpu: 2
  memory: 8G

task:
  name: tests
  script: ./gradlew test

task:
  name: debug-build

  depends_on:
    - tests

  script: |
    ./download-bootstraps.sh
    ./gradlew assembleDebug

  output_artifacts:
    path: "./app/build/outputs/apk/debug/*.apk"
